import { PERMISSIONS } from "./permissions.js";

export const ADMIN_ROLE_PERMISSIONS = {
 
  product_manager: [PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_WRITE],

  order_manager: [
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_WRITE,
    PERMISSIONS.RECOVERY_READ,
    PERMISSIONS.RECOVERY_WRITE,
  ],


  customer_support: [
    PERMISSIONS.REFUND_READ,
    PERMISSIONS.RECOVERY_READ,
    PERMISSIONS.RECOVERY_WRITE,
  ],

  
  supervisor: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.REFUND_READ,
    PERMISSIONS.COUPON_READ,
    PERMISSIONS.AUDIT_READ,
  ],


  super_admin: Object.values(PERMISSIONS),
};
